name: Docker Image CI

on:
  push:
    branches: [ "master" ]
    
env:
  TAG: $(date +%s)

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag antgilles/algassignement:$TAG
    - name: Login on DockerHub
      run: docker login -u antgilles -p ${{ secrets.GH_PASS }}
    - name: Push on DockerHub
      run: docker push antgilles/algassignement:$TAG
